resources:
 - ../../base/mq-qm01
 # - queuemanager/hooks/post-sync-job.yaml
 # - certificates/staging-mq-client-certificate.yaml
 # - certificates/staging-mq-server-certificate.yaml
 # - secrets/mq-client-jks-password-secret.yaml
 - roles/cphtestp-clusterrole.yaml
 - roles/cphtestp-sa-rolebinding.yaml
generatorOptions:
 disableNameSuffixHash: true
# We use a configMapGenerator because it allows us to build up the mqsc from regular MQSC files.
configMapGenerator:
# Create an MQSC configMap using generic MQSC which will be added to all queue managers and applied during bootstrap.
- name: mqsc-configmap
  behavior: create
  files:
  - configmap/static-definitions.mqsc
patchesStrategicMerge:
 - queuemanager/queuemanager.yaml
