apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgBfdMIaVz2xeqcK9Dy/nacnUvFhvvFV4eqIullkr4dot9ZacPC8RCkD2jy5NGLR1FY27uJzTTcOIbYqQBmewlUX2RABqBHrPwsBUR9mOpq1NYQrLLrwDyJUq0Iz5RXbdTKvH/CDmGCyVeusYwgwnrld0CmHkCpE4vhF+BKa8dQVeJNsm5kPspDx58oewjXUXAe/fSLqJ1y8h4WZreP4dV8nFxjlBhD0JwEeS7gZHz8UWcEIQ6A2spdSO999/dRFtOdXjGjmqMwTmRh9nu3JksBrPL76vuEIwWbgwHfhN0Wk/wcmH8fibWpecZ3dAhH8nFir7WsFA8LomMxY66RqSW29c7sBBTuYIVpksIOnoaQ7KZ1jFrhl3LPR1jbst/A5vRgpStLfHejRxyiMyw74IALPQU9EzH9fJmAbSzqeO4pX2Ct1lOc3xuObUUCCg9bgkV84ZAXcCl2x2Lr0MJFOIaYXhSTmDGT7hTBu6E0a7+hc6kmwsoKdzlLf0EvDEPwbejf1JAoiUigiHakLbxAMUzFkwIGB3bH519pNxlpf7bThxtYJm39oxIyuEwRxczOZRkfqrAQeJC0KH3IB6YEfQd88eSBVcDw9LhusiERJZDL91uUByvdDz5idZSk41BKdGMhLv1JnDZpySwxECJ4AY4WB1wiPpfUnKTp8kiDxPEv9FGcyOm1nT8ITmTODEmH4aHCGebNqyOyh14Bg1UUlADblyzBxIPn+sA501feynDuxHY5R2sQa1DD/ZI9PAnIBk6tOZEQ0+pBYa4Cj5sp94lFJdmkRlTfBWX6N+ktoV7kOie9h1MCBm+aRw9STxXTjTSu0bsWnm+PbQlRHVflzmRbvwSjL9bvIvRIL8MTlKwgAoOwdxG3igyfhH4bQa+ghog7kY0G4MQ3tzCGGPui3x1d3bG5FlWTRKtbDo0DBfpjWmX09/K6+f3sQVVlQCbeQHP1TmIztpfR6DRVKIBcEMr9BPDBHMVXs+4/iFHoDt9skQXNxMF84zjt+HxiTpbPb1GROAcKua9EJ7wbR6zE2ClnPjGyz07JeM2bd4cOaqI2C6rphr2HGDAnzhLpjTJyXly9Fla6gkwHs4FMoxJPfx6BKTJWEOCRMiSXfHHu3/+Y7CBpmqny60jOVIeWEUz+iJ2qrMrXF1aFJCHy/uZpoDr5M0qdxIbN7Urdx9LBmAjGw7Df4MZ0T5gSC6gt0JnhhPt6Yu9ghfO9SJnsFnRX8ptAwCIPnhQ+6dvnMofLHs3sjX0syqBmA/5LsIgHOyLpMI3Xtf47XlQaL7jzTOy30SVVL7+en38IIrj0IhGfQ9di6fVvp1G/jSb4B+IN0aHCJHJuY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

